use_frameworks!

target 'ARMDevSuite_Example' do
  pod 'ARMDevSuite', :path => '../'
  pod 'JGProgressHUD', :inhibit_warnings => true

  target 'ARMDevSuite_Tests' do
    inherit! :search_paths

    
    
  end
end
